name: Gource Action
on:
  push:
    branches:
      - master
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          gource_resolution: '1080p'
          avatars_auto_fetch: true

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4
